version: "3.7"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - 5432:5432

volumes:
  postgres_data: {}
